import type { ProjectFile } from "../types";
import { DEFAULT_PARAMS, DEFAULT_CT_PARAMS } from "../defaults";

// Full plant distribution covering every workplace voltage level:
// 132 kV grid intake → 33 kV → 11 kV, then split to a 6.6 kV motor board and
// a 525 V LV board. Breakers, CTs and relays at the intake and motor feeders.
// Exercises load flow, short circuit, motor starting, grading and arc flash
// across the whole hierarchy.
export const fullPlant132_525: ProjectFile = {
  version: "1.0",
  metadata: { name: "Full plant — 132 kV to 525 V", created: "2026-06-17", modified: "2026-06-17" },
  system: { base_mva: 100, frequency_hz: 50 },
  components: [
    {
      id: "SRC-1",
      type: "grid_source",
      label: "GRID-132",
      position: { x: 360, y: 0 },
      parameters: { nominal_voltage_kv: 132, short_circuit_mva: 3500, xr_ratio: 15, scheduled_mw: 0 },
    },
    {
      id: "Q-IN",
      type: "switch",
      label: "Q-INTAKE",
      position: { x: 380, y: 70 },
      parameters: { closed: true, device_type: "breaker" },
    },
    {
      id: "RLY-IN",
      type: "relay",
      label: "RLY-INTAKE",
      position: { x: 500, y: 65 },
      parameters: { ...DEFAULT_PARAMS.relay, relay_model: "ABB-REM615", curve: "IEC-VI", plug_setting: 1.0, time_multiplier: 0.3, measured_connection_id: "conn-src-q" },
    },
    {
      id: "BB-132",
      type: "busbar",
      label: "BB-132",
      position: { x: 280, y: 150 },
      parameters: { nominal_voltage_kv: 132, length_px: 260, arc_equipment_class: "switchgear", arc_grounded: true, arc_electrode_config: "VCB" },
    },
    {
      id: "TX-1",
      type: "transformer",
      label: "TX-132/33",
      position: { x: 360, y: 230 },
      parameters: { rated_mva: 40, primary_kv: 132, secondary_kv: 33, impedance_percent: 12, xr_ratio: 20, vector_group: "YNd11" },
    },
    {
      id: "BB-33",
      type: "busbar",
      label: "BB-33",
      position: { x: 280, y: 320 },
      parameters: { nominal_voltage_kv: 33, length_px: 260, arc_equipment_class: "switchgear", arc_grounded: true, arc_electrode_config: "VCB" },
    },
    {
      id: "TX-2",
      type: "transformer",
      label: "TX-33/11",
      position: { x: 360, y: 400 },
      parameters: { rated_mva: 20, primary_kv: 33, secondary_kv: 11, impedance_percent: 10, xr_ratio: 15, vector_group: "Dyn11" },
    },
    {
      id: "BB-11",
      type: "busbar",
      label: "BB-11",
      position: { x: 160, y: 490 },
      parameters: { nominal_voltage_kv: 11, length_px: 520, arc_equipment_class: "switchgear", arc_grounded: true, arc_electrode_config: "VCB" },
    },
    {
      id: "TX-3",
      type: "transformer",
      label: "TX-11/6.6",
      position: { x: 150, y: 570 },
      parameters: { rated_mva: 8, primary_kv: 11, secondary_kv: 6.6, impedance_percent: 7, xr_ratio: 12, vector_group: "Dyn11" },
    },
    {
      id: "BB-66",
      type: "busbar",
      label: "BB-6.6",
      position: { x: 60, y: 660 },
      parameters: { nominal_voltage_kv: 6.6, length_px: 280, arc_equipment_class: "switchgear", arc_grounded: true, arc_electrode_config: "VCB" },
    },
    {
      id: "Q-M",
      type: "switch",
      label: "Q-MOTOR",
      position: { x: 110, y: 740 },
      parameters: { closed: true, device_type: "breaker" },
    },
    {
      id: "RLY-M",
      type: "relay",
      label: "RLY-MOTOR",
      position: { x: 240, y: 735 },
      parameters: { ...DEFAULT_PARAMS.relay, relay_model: "GE-869", curve: "IEEE-MI", plug_setting: 1.2, time_multiplier: 0.1, thermal_enabled: true, thermal_k: 1.1, thermal_curve_mult: 4, thermal_base_a: 0, measured_connection_id: "conn-bb66-qm" },
    },
    {
      id: "CBL-M",
      type: "cable",
      label: "MTR-CBL",
      position: { x: 110, y: 810 },
      parameters: { resistance_ohm_per_km: 0.16, reactance_ohm_per_km: 0.1, length_m: 250, ampacity_a: 350, csa_mm2: 185 },
    },
    {
      id: "M-1",
      type: "motor",
      label: "M-6.6kV",
      position: { x: 90, y: 880 },
      parameters: { rated_kw: 2500, power_factor: 0.88, efficiency: 0.95, locked_rotor_current_ratio: 6, starting_method: "DOL", starting_pf: 0.2, starting_time_s: 8 },
    },
    {
      id: "TX-4",
      type: "transformer",
      label: "TX-11/0.525",
      position: { x: 470, y: 570 },
      parameters: { rated_mva: 2, primary_kv: 11, secondary_kv: 0.525, impedance_percent: 6, xr_ratio: 8, vector_group: "Dyn11" },
    },
    {
      id: "BB-525",
      type: "busbar",
      label: "BB-525V",
      position: { x: 380, y: 660 },
      parameters: { nominal_voltage_kv: 0.525, length_px: 300, arc_equipment_class: "MCC", arc_grounded: true, arc_electrode_config: "VCB" },
    },
    {
      id: "LD-LV",
      type: "load",
      label: "LV-LOAD",
      position: { x: 360, y: 740 },
      parameters: { active_power_kw: 400, reactive_power_kvar: 150 },
    },
    {
      id: "CBL-LV",
      type: "cable",
      label: "LV-MTR-CBL",
      position: { x: 520, y: 740 },
      parameters: { resistance_ohm_per_km: 0.39, reactance_ohm_per_km: 0.08, length_m: 80, ampacity_a: 500, csa_mm2: 95 },
    },
    {
      id: "M-2",
      type: "motor",
      label: "M-525V",
      position: { x: 520, y: 820 },
      parameters: { rated_kw: 250, power_factor: 0.86, efficiency: 0.93, locked_rotor_current_ratio: 6.5, starting_method: "DOL", starting_pf: 0.2, starting_time_s: 4 },
    },
  ],
  connections: [
    { id: "conn-src-q", fromComponent: "SRC-1", fromTerminal: "out", toComponent: "Q-IN", toTerminal: "in", ct: { ...DEFAULT_CT_PARAMS, primary_a: 200, secondary_a: 1 } },
    { id: "conn-q-bb132", fromComponent: "Q-IN", fromTerminal: "out", toComponent: "BB-132", toTerminal: "top" },
    { id: "conn-rly-in", fromComponent: "RLY-IN", fromTerminal: "trip", toComponent: "Q-IN", toTerminal: "in" },
    { id: "conn-bb132-tx1", fromComponent: "BB-132", fromTerminal: "bottom", toComponent: "TX-1", toTerminal: "primary" },
    { id: "conn-tx1-bb33", fromComponent: "TX-1", fromTerminal: "secondary", toComponent: "BB-33", toTerminal: "top" },
    { id: "conn-bb33-tx2", fromComponent: "BB-33", fromTerminal: "bottom", toComponent: "TX-2", toTerminal: "primary" },
    { id: "conn-tx2-bb11", fromComponent: "TX-2", fromTerminal: "secondary", toComponent: "BB-11", toTerminal: "top" },
    { id: "conn-bb11-tx3", fromComponent: "BB-11", fromTerminal: "bottom", toComponent: "TX-3", toTerminal: "primary" },
    { id: "conn-tx3-bb66", fromComponent: "TX-3", fromTerminal: "secondary", toComponent: "BB-66", toTerminal: "top" },
    { id: "conn-bb66-qm", fromComponent: "BB-66", fromTerminal: "bottom", toComponent: "Q-M", toTerminal: "in", ct: { ...DEFAULT_CT_PARAMS, primary_a: 300, secondary_a: 1 } },
    { id: "conn-qm-cbl", fromComponent: "Q-M", fromTerminal: "out", toComponent: "CBL-M", toTerminal: "from" },
    { id: "conn-rly-m", fromComponent: "RLY-M", fromTerminal: "trip", toComponent: "Q-M", toTerminal: "in" },
    { id: "conn-cblm-m", fromComponent: "CBL-M", fromTerminal: "to", toComponent: "M-1", toTerminal: "in" },
    { id: "conn-bb11-tx4", fromComponent: "BB-11", fromTerminal: "bottom", toComponent: "TX-4", toTerminal: "primary" },
    { id: "conn-tx4-bb525", fromComponent: "TX-4", fromTerminal: "secondary", toComponent: "BB-525", toTerminal: "top" },
    { id: "conn-bb525-ld", fromComponent: "BB-525", fromTerminal: "bottom", toComponent: "LD-LV", toTerminal: "in" },
    { id: "conn-bb525-cbl", fromComponent: "BB-525", fromTerminal: "bottom", toComponent: "CBL-LV", toTerminal: "from" },
    { id: "conn-cbllv-m", fromComponent: "CBL-LV", fromTerminal: "to", toComponent: "M-2", toTerminal: "in" },
  ],
};
