import type { ProjectFile } from "../types";

export const industrialPlant: ProjectFile = {
  version: "1.0",
  metadata: { name: "Industrial plant", created: "2026-05-25", modified: "2026-05-25" },
  system: { base_mva: 20, frequency_hz: 50 },
  components: [
    {
      id: "SRC-1",
      type: "grid_source",
      label: "INCOMER",
      position: { x: 280, y: 20 },
      parameters: { nominal_voltage_kv: 33, short_circuit_mva: 1200, xr_ratio: 14, scheduled_mw: 0 },
    },
    {
      id: "BB-HV",
      type: "busbar",
      label: "HV-33",
      position: { x: 200, y: 100 },
      parameters: { nominal_voltage_kv: 33, length_px: 240 },
    },
    {
      id: "TX-1",
      type: "transformer",
      label: "TX-MAIN",
      position: { x: 280, y: 180 },
      parameters: { rated_mva: 8, primary_kv: 33, secondary_kv: 11, impedance_percent: 8, xr_ratio: 18, vector_group: "Dyn11" },
    },
    {
      id: "BB-MV",
      type: "busbar",
      label: "MV-MAIN",
      position: { x: 60, y: 300 },
      parameters: { nominal_voltage_kv: 11, length_px: 560 },
    },
    {
      id: "TX-2",
      type: "transformer",
      label: "TX-FDR1",
      position: { x: 130, y: 400 },
      parameters: { rated_mva: 1.6, primary_kv: 11, secondary_kv: 0.4, impedance_percent: 6, xr_ratio: 12, vector_group: "Dyn11" },
    },
    {
      id: "TX-3",
      type: "transformer",
      label: "TX-FDR2",
      position: { x: 470, y: 400 },
      parameters: { rated_mva: 1.6, primary_kv: 11, secondary_kv: 0.4, impedance_percent: 6, xr_ratio: 12, vector_group: "Dyn11" },
    },
    {
      id: "BB-LV1",
      type: "busbar",
      label: "LV-FDR1",
      position: { x: 30, y: 520 },
      parameters: { nominal_voltage_kv: 0.4, length_px: 240 },
    },
    {
      id: "BB-LV2",
      type: "busbar",
      label: "LV-FDR2",
      position: { x: 370, y: 520 },
      parameters: { nominal_voltage_kv: 0.4, length_px: 240 },
    },
    {
      id: "LD-1",
      type: "load",
      label: "PROC-LD1",
      position: { x: 50, y: 610 },
      parameters: { active_power_kw: 400, reactive_power_kvar: 150 },
    },
    {
      id: "M-1",
      type: "motor",
      label: "PUMP-M1",
      position: { x: 200, y: 610 },
      parameters: { rated_kw: 200, power_factor: 0.87, efficiency: 0.93, locked_rotor_current_ratio: 6.5, starting_method: "soft-starter", starting_pf: 0.3 },
    },
    {
      id: "LD-2",
      type: "load",
      label: "PROC-LD2",
      position: { x: 390, y: 610 },
      parameters: { active_power_kw: 500, reactive_power_kvar: 180 },
    },
    {
      id: "M-2",
      type: "motor",
      label: "FAN-M2",
      position: { x: 540, y: 610 },
      parameters: { rated_kw: 160, power_factor: 0.86, efficiency: 0.93, locked_rotor_current_ratio: 6.0, starting_method: "VFD", starting_pf: 0.95 },
    },
  ],
  connections: [
    { id: "conn-1", fromComponent: "SRC-1", fromTerminal: "out", toComponent: "BB-HV", toTerminal: "top" },
    { id: "conn-2", fromComponent: "BB-HV", fromTerminal: "bottom", toComponent: "TX-1", toTerminal: "primary" },
    { id: "conn-3", fromComponent: "TX-1", fromTerminal: "secondary", toComponent: "BB-MV", toTerminal: "top" },
    { id: "conn-4", fromComponent: "BB-MV", fromTerminal: "bottom", toComponent: "TX-2", toTerminal: "primary" },
    { id: "conn-5", fromComponent: "TX-2", fromTerminal: "secondary", toComponent: "BB-LV1", toTerminal: "top" },
    { id: "conn-6", fromComponent: "BB-MV", fromTerminal: "bottom", toComponent: "TX-3", toTerminal: "primary" },
    { id: "conn-7", fromComponent: "TX-3", fromTerminal: "secondary", toComponent: "BB-LV2", toTerminal: "top" },
    { id: "conn-8", fromComponent: "BB-LV1", fromTerminal: "bottom", toComponent: "LD-1", toTerminal: "in" },
    { id: "conn-9", fromComponent: "BB-LV1", fromTerminal: "bottom", toComponent: "M-1", toTerminal: "in" },
    { id: "conn-10", fromComponent: "BB-LV2", fromTerminal: "bottom", toComponent: "LD-2", toTerminal: "in" },
    { id: "conn-11", fromComponent: "BB-LV2", fromTerminal: "bottom", toComponent: "M-2", toTerminal: "in" },
  ],
};
